### PR TITLE
clojure.core/keys and clojure.core/vals accept nil input

### PR DESCRIPTION
**Pull request by martintrojer**

### CODE REVIEW

**Comment by frenchy64** [comment]
It's unclear whether `nil` is a supported input of `keys`. Would like to hear a convincing case from an authority on the matter.

**Comment by seancorfield** [comment]
FWIW clojuredocs.org shows `(keys nil)` and `(vals nil)` in the examples and both functions' docstrings imply very strongly that `(seq map)` is called (for their argument `map`) which would suggest they intentionally treat `nil` and `{ }` identically.

**Comment by frenchy64** [comment]
Some interesting history here:
https://github.com/clojure/clojure/commit/d93ef6293bbcc6059e6da77dbf6ed26167f36cdb

**Comment by frenchy64** [comment]
I also noticed there's no test for `(keys nil)` in the clojure repo, even though there's lots of succeeding tests for non-map things.

**Comment by frenchy64** [comment]
It seems the commit that was reverted actually explicitly handled IPersistentMaps and `nil` and threw an error on everything else. It was reverted because it apparently broke `subseq`.

**Comment by seancorfield** [comment]
My reading of that is that `coll == null` is explicitly intended to be allowed because it was special cased in the commit to avoid NPE and in both the before and after code it's supported by `(seq coll)`. I agree it's odd there are no explicit tests for it tho'.

**Comment by frenchy64** [comment]
That sounds convincing. I'll sleep on it.

**Comment by frenchy64** [comment]
@arohner have we had this conversation about `keys` before?

**Comment by arohner** [comment]
It sounds familiar. I know we've had similar conversations. 

I think it comes down to the desired philosophy of core.typed. Should core.typed be prescriptive or descriptive? I've always been interested in using core.typed for pragmatic, productive work, so I've always come down firmly on the descriptive side, because otherwise core.typed will reject "legal" code that clojure.core will accept. IMO core.typed should *always* match the behavior of clojure, even if we think that behavior is weird or strange.

**Comment by frenchy64** [comment]
Good points.

It made me think harder about _why_ I care about these kinds of nitpicks. It comes down to forwards compatibility: I don't want to "fix" annotations to be less permissive as new versions of Clojure come out -- perhaps with better error checking or documentation. I want core.typed to show you how to write robust code that will work in the future. I'm interpreting the current implementation+documentation+history into a type annotation that is intended to guide the programmer to the "correct" usage of a clojure feature.

But that reasoning doesn't fully check out. For one, if a function becomes more restrictive... just change the annotation! core.typed will tell you all the places you were depending on previous (perhaps weird/strange) behaviour. And, as you said, if it works it ain't broke. It just makes core.typed more painful to use ("a necessary loss" was my justification).

**Comment by frenchy64** [comment]
Perhaps a "compatibility mode" is a solution. By default, have annotations that are in the spirit of the current approach (ie. "fix" Clojure). Then a per-namespace flag in the ns-form that give the _actual_ annotations for core Clojure.

**Comment by frenchy64** [comment]
I have some year-old data about how CircleCI uses core.typed. Would probably be used to see if all these things are still being checked.

```
src/circle/admin/iam.clj
8 checked annotations
1 HMap defalias

src/circle/airbrake.clj
2 checked
3 unchecked
Notes: slingshot problematic

src/circle/aws/credentials.clj

1 checked
2 unchecked
Notes: deftype constructor usage

src/circle/aws/ec2.clj

1 library annotation
1 non-nil-return annotation
Line 107: casted nullable Java method
3 var annotation
6 no-check var annotations

src/circle/backend/action.clj

1 ann-record
1 no-check ann
Line 65: Keyword arguments
Notes: Effectively untyped

src/circle/backend/container_fs.clj

4 ann
7 nocheck
Notes: Slingshot

src/circle/backend/container_fs/btrfs.clj

8 ann
11 no-check ann
Kw args
Slingshot accounts for 1 no-check
1 ann-record

src/circle/backend/container_fs/image.clj

8 ann
Uses throw+ successfully?
Type hints with core.typed
2 no-check ann

src/circle/backend/container_fs/protocol.clj

1 HMap defalias
1 defprotocol

src/circle/backend/disk.clj

2 checked
1 unchecked
Note: if `vec` knew a nonempty sequence meant a non-empty vec, then 3 checked

src/circle/backend/ec2.clj

1 no-checked annotation
Kw args

src/circle/backend/lxc.clj

2 defalias
2 ann
16 no-check ann
Slingshot accounts for 2 no-check

src/circle/backend/lxc/config.clj

2 ann
2 Kw args
2 no-check ann

src/circle/backend/ssh.clj

3 HMap defalias's
1 non-HMap defalias
3 library annotations
5 ann
3 no-check
2 Kw args

Note: very interesting security usage, ensure private key is dissociated line 66.
      Would love to use this as an example!!
      {encrypt,decrypt}-keypair

src/circle/backend/sshfs.clj

1 HMap defalias
1 non-HMap defalias
2 ann

Note: INTERESTING security code? Mount/unmount ssh sessions, w/ private keys

src/circle/capabilities.clj

15 ann

src/circle/config.clj

2 ann
2 no-check ann

Note: INTERESTING usage of Java method nullable returns

src/circle/db.clj

1 ann
2 no-check

swap! assoc-in pattern (1 no-check)

src/circle/email.clj

1 HMap defalias
1 non-HMap defalias
1 external ann
1 ann
2 no-check ann
2 Kw args

get-in accounted for 1 no-check
Also used metadata in 1 no-check

src/circle/env.clj

8 ann

Note: (Is this ever checked?)

src/circle/experiment.clj

1 ann
8 no-check ann

Note: (Is this ever checked?)

src/circle/feature.clj

1 tc-ignore
Type check custom records that implement IFn
1 polymorphic record
2 ann
4 no-check
4 Polymorphic functions
2 usages of latent filters

get-in accounts for 1 no-check

Comment about another reason to do with mongo about type checking
Another comment: convince core.typed about `for` loop

Note: interesting filter usage, might want to revisit

src/circle/github/cache.clj

3 ann
4 no-check
1 Non-hmap defalias

Note: definition of `lookup` is interesting

src/circle/github/urls.clj

1 ann

src/circle/github/user.clj

16 ann
1 no-check

Note: !! Unlikely to ever be check-ns'd

src/circle/globals.clj

3 ann

src/circle/hipchat.clj

12 ann
5 no-check ann

Note: ns circular dependency issue between types

src/circle/http/assets.clj

2 no-checked ann

Note: ever checked?

src/circle/http/authentication.clj

1 HMap defalias
3 ann
1 usage of function intersection (2 arities, 0 and 1 args)

src/circle/http/authentication/login.clj

1 non-HMap defalias
7 ann

Note: ever checked?

src/circle/http/authorization.clj

1 non-HMap defalias
7 ann
3 IFn overload (different arities)

src/circle/http/builds.clj

1 ann

Note: never checked? but useful documentation

src/circle/http/defpage.clj
6 ann
1 nocheck

src/circle/http/salesforce.clj
5 library
46 nocheck
6 ann

src/circle/model/container.clj
8 ann

INTERESTING PRIVATE KEY STUFF


src/circle/model/github_api_cache.clj
2 ann
2 HMap defalias

src/circle/model/organization.clj
1 ann
5 nocheck

src/circle/model/plan.clj
10 ann
2 nocheck

src/circle/model/project.clj
25 ann
19 nocheck
11 HMap defalias

src/circle/model/scope.clj
2 ann
1 nocheck

src/circle/model/settings.clj
2 nocheck 

src/circle/model/test.clj
1 HMap defalias

src/circle/model/user_project_perm.clj
10 ann
1 HMap defalias

src/circle/notifications.clj
3 nocheck

src/circle/s3.clj
2 ann
6 nocheck

src/circle/sh.clj
1 non-HMap defalias (Map)
7 ann
6 external ann
6 nocheck

src/circle/tasks/deploy.clj
6 ann
probably not checked

src/circle/util/coerce.clj
2 ann

src/circle/util/core.clj
18 ann
4 nocheck

src/circle/util/crypto.clj
4 external 

src/circle/util/except.clj
1 ann
2 nocheck 

src/circle/util/fj.clj
4 external 
2 ann

src/circle/util/fs.clj
4 nocheck
5 ann

src/circle/util/hall_notify.clj
1 HMap defalias
1 non-HMap defalias (Map)
1 ann
1 nocheck

src/circle/util/http.clj
2 ann

src/circle/util/java/streams.clj
1 ann
1 kwargs

src/circle/util/map.clj
2 ann

src/circle/util/mongo.clj
2 ann

src/circle/util/mount.clj
4 ann

src/circle/util/predicates.clj
4 ann
2 nocheck

src/circle/util/re.clj
4 ann
1 kwargs

src/circle/util/ref.clj
1 ann
2 non-HMap defalias

src/circle/util/retry.clj
1 nocheck

src/circle/util/s3_versioned_resource.clj
1 ann
2 nocheck

src/circle/util/sed.clj
2 ann

src/circle/util/semantic_version.clj
5 ann
2 nocheck

src/circle/util/seq.clj
1 ann
1 nocheck

src/circle/util/slack_notify.clj
1 ann
3 nocheck

src/circle/util/straight_jacket.clj
1 ann

src/circle/util/string.clj
1 ann

src/circle/util/time.clj
1 ann
1 nocheck

src/circle/util/type/ann.clj
100 external ann
11 non-nil-return
9 non-HMap defaliases
12 HMap defaliases

src/circle/util/type/ann/datomic.clj
3 external ann
7 non-HMap defalias

src/circle/util/typed_string.clj
3 ann
```

**Comment by arohner** [comment]
> Perhaps a "compatibility mode" is a solution. By default, have annotations that are in the spirit of the current approach 

Getting started with core.typed is still pretty difficult, largely because there are a lot of things that don't work out of the box. Intentionally making the annotations not match Clojure by default sounds like an extra hurdle that doesn't need to be there.

**Comment by frenchy64** [comment]
Yes, core.typed doesn't take the user experience very seriously, especially if it means making more programs type check.

Perhaps a good compromise are warnings on "undefined behaviour", or what I've been interpreting as that, and giving the real annotations by default.

**Comment by frenchy64** [comment]
@martintrojer please submit a Jira issue for this. This patch won't work because of the `:object` assigned to `keys`.

I would greatly appreciate Jira issues being the first avenue for bug reports.

**Pull request closed without merging**
